#!/usr/bin/env sh

if [ $# != 1 ];
then
   echo "ERROR: illegal number of arguments ($#), expected exactly 1 parameter expected with value groupId (e.g. 'fr.xebia.demo.petclinic-team-5')"
   exit 1
fi

GROUP_ID=$1
ARTIFACT_ID="xebia-petclinic"
VERSION="LATEST"
REPOSITORY="snapshots"
HEALT_CHECK_URL="http://localhost:8080/xebia-petclinic/"

# shutdown tomcat
/usr/sbin/tomcat6 stop
 
# cleanup
if [ -f /usr/share/tomcat6/webapps/xebia-petclinic.war ];
then
   rm -rf "/usr/share/tomcat6/webapps/xebia-petclinic.war"
fi
if [ -d /usr/share/tomcat6/webapps/xebia-petclinic ];
then
   rm -rf "/usr/share/tomcat6/webapps/xebia-petclinic"
fi

echo "petclinic removed from tomcat server"

# download new war version
echo "Download '$GROUP_ID:$ARTIFACT_ID:$VERSION' from '$REPOSITORY' repository"
curl "http://nexus.xebia-tech-event.info:8081/nexus/service/local/artifact/maven/content?g=$GROUP_ID&a=$ARTIFACT_ID&r=$REPOSITORY&v=$VERSION&e=war" --silent --show-error  --output "/usr/share/tomcat6/webapps/xebia-petclinic.war"

echo "petclinic downloaded from nexus server"

# start tomcat
/usr/sbin/tomcat6 start

echo "petclinic tomcat started"

# test started webapp
# TODO: should return error in case of wrong http response
sleep 30

HEALTH_CHECK_HTTP_CODE=$(curl --connect-timeout 10 --retry 10 --silent --show-error -w "%{http_code}" -o /dev/null $HEALT_CHECK_URL) 
if [ $HEALTH_CHECK_HTTP_CODE -eq 200 ];
then
   echo "Health check url $HEALT_CHECK_URL returned expected http code '$HEALTH_CHECK_HTTP_CODE'"
else
   echo "FAILURE: '$GROUP_ID:$ARTIFACT_ID:$VERSION' deployed on tomcat server but health check '$HEALT_CHECK_URL' is KO (returned '$HEALTH_CHECK_HTTP_CODE')"
   exit 1
fi

echo "SUCCESS: '$GROUP_ID:$ARTIFACT_ID:$VERSION' deployed and available on tomcat server"